name: Mercatia Fork of StockMarket Simulator

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: 
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        working-directory: ./Backend
        run: mvn clean package -DskipTests

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup docker builds
        uses: docker/setup-buildx-action@v1
      
      - name: loging to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Docker meta
        id: onviffmqtt
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/mercatia/stockmarketsimulator
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha


      - name: build and push
        uses: docker/build-push-action@v2
        working-directory: ./Backend
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}}}
